# Generated by Django 4.2.7 on 2023-11-30 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('ruc', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_DePago', models.CharField(choices=[('interfisa', 'interfisa'), ('tigo-349', 'tigo-349'), ('tigo-757', 'tigo-757'), ('tigo-722', 'tigo-722'), ('zimple-349', 'zimple-349'), ('zimple-757', 'zimple-757'), ('zimple-722', 'zimple-722'), ('wally-349', 'wally-349'), ('wally-757', 'wally-757'), ('wally-722', 'wally-722')], max_length=50)),
                ('monto', models.IntegerField()),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('transaccion_img', models.ImageField(blank=True, upload_to='transacciones')),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='giro.cliente')),
            ],
        ),
    ]
