# Generated by Django 4.2.7 on 2023-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='transaccion_img',
            field=models.ImageField(blank=True, upload_to='transacciones', verbose_name='Foto'),
        ),
    ]
