# Generated by Django 4.2.7 on 2023-11-30 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giro', '0002_alter_transaccion_transaccion_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
