# Generated by Django 4.2.7 on 2023-11-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giro', '0003_transaccion_editado_transaccion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cobrado'),
        ),
    ]
