# Generated by Django 4.2.7 on 2023-11-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giro', '0004_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
