# Generated by Django 4.2.7 on 2023-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giro', '0005_alter_transaccion_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_pais',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
