# Generated by Django 5.0.6 on 2024-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('E', 'Enviado'), ('R', 'Rechazado')], default='P', max_length=1),
        ),
    ]
