# Generated by Django 5.0.6 on 2024-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0002_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='caja',
            field=models.CharField(choices=[('G', 'Giro'), ('I', 'Interfisa')], default='G', max_length=50),
        ),
    ]
