# Generated by Django 5.0.6 on 2024-07-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0003_transaccion_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='caja',
            field=models.CharField(blank=True, choices=[('G', 'Giro'), ('I', 'Interfisa')], max_length=50, null=True),
        ),
    ]
