# Generated by Django 5.0.6 on 2024-07-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0004_alter_transaccion_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='num_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
