# Generated by Django 5.0.6 on 2024-08-26 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0009_alter_transaccion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='agregado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='caja',
            field=models.CharField(blank=True, choices=[('G', 'Giro'), ('I', 'Interfisa')], max_length=50, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remesas.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='entidad',
            field=models.CharField(choices=[('BANCOP S.A.', 'BANCOP S.A.'), ('Banco Atlas S.A.', 'Banco Atlas S.A.'), ('Banco BASA', 'Banco BASA'), ('Banco Continental S.A.E.C.A.', 'Banco Continental S.A.E.C.A.'), ('Banco Familiar S.A.E.C.A.', 'Banco Familiar S.A.E.C.A.'), ('Banco GNB - Paraguay', 'Banco GNB - Paraguay'), ('Banco Itaú Paraguay S.A.', 'Banco Itaú Paraguay S.A.'), ('Banco Nacional de Fomento (BNF)', 'Banco Nacional de Fomento (BNF)'), ('Banco Rio S.A.E.C.A', 'Banco Rio S.A.E.C.A'), ('COOPEDUC Ltda.', 'COOPEDUC Ltda.'), ('COPACONS Ltda.', 'COPACONS Ltda.'), ('Cooperativa 21 de Setiembre Ltda.', 'Cooperativa 21 de Setiembre Ltda.'), ('Cooperativa Alemán Concordia Ltda.', 'Cooperativa Alemán Concordia Ltda.'), ('Cooperativa Chortitzer Ltda.', 'Cooperativa Chortitzer Ltda.'), ('Cooperativa Coodeñe Ltda.', 'Cooperativa Coodeñe Ltda.'), ('Cooperativa Colonias Unidas Ltda.', 'Cooperativa Colonias Unidas Ltda.'), ('Cooperativa Coomecipar Ltda.', 'Cooperativa Coomecipar Ltda.'), ('Cooperativa de las Fuerzas Armadas de la Nación Ltda.', 'Cooperativa de las Fuerzas Armadas de la Nación Ltda.'), ('Cooperativa Fernheim Ltda.', 'Cooperativa Fernheim Ltda.'), ('Cooperativa Mborayhu Ltda.', 'Cooperativa Mborayhu Ltda.'), ('Cooperativa Mburicao Ltda.', 'Cooperativa Mburicao Ltda.'), ('Cooperativa Medalla Milagrosa Ltda.', 'Cooperativa Medalla Milagrosa Ltda.'), ('Cooperativa Mercado 4 Ltda.', 'Cooperativa Mercado 4 Ltda.'), ('Cooperativa Multiactiva 8 de Marzo Ltda.', 'Cooperativa Multiactiva 8 de Marzo Ltda.'), ('Cooperativa Naranjal Ltda.', 'Cooperativa Naranjal Ltda.'), ('Cooperativa Nazareth Ltda.', 'Cooperativa Nazareth Ltda.'), ('Cooperativa Neuland Ltda.', 'Cooperativa Neuland Ltda.'), ('Cooperativa Ñemby Ltda.', 'Cooperativa Ñemby Ltda.'), ('Cooperativa Raúl Peña Ltda.', 'Cooperativa Raúl Peña Ltda.'), ('Cooperativa San Ignacio', 'Cooperativa San Ignacio'), ('Cooperativa San Juan Bautista Ltda.', 'Cooperativa San Juan Bautista Ltda.'), ('Cooperativa Universitaria Ltda.', 'Cooperativa Universitaria Ltda.'), ('Cooperativa Ypacarai Ltda.', 'Cooperativa Ypacarai Ltda.'), ('Financiera Paraguayo Japonesa S.A.E.C.A', 'Financiera Paraguayo Japonesa S.A.E.C.A'), ('FINANCIERA FIC S.A.E.C.A.', 'FINANCIERA FIC S.A.E.C.A.'), ('Interfisa Banco', 'Interfisa Banco'), ('Solar Banco S.A.E.', 'Solar Banco S.A.E.'), ('Sudameris Bank S.A.E.C.A.', 'Sudameris Bank S.A.E.C.A.'), ('TIGO BANK', 'TIGO BANK'), ('TIGO-349', 'TIGO-349'), ('TIGO-722', 'TIGO-722'), ('TIGO-757', 'TIGO-757'), ('Tu Financiera', 'Tu Financiera'), ('Ueno', 'Ueno'), ('Visión Banco S.A.E.C.A.', 'Visión Banco S.A.E.C.A.'), ('WALLY-349', 'WALLY-349'), ('WALLY-722', 'WALLY-722'), ('WALLY-757', 'WALLY-757'), ('ZETA Banco', 'ZETA Banco'), ('ZIMPLE-349', 'ZIMPLE-349'), ('ZIMPLE-722', 'ZIMPLE-722'), ('ZIMPLE-757', 'ZIMPLE-757')], max_length=100, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('E', 'Enviado'), ('R', 'Rechazado')], default='P', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='imagen_comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='num_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de comprobante'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última modificación'),
        ),
    ]
