# Generated by Django 5.0.6 on 2024-08-26 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remesas', '0008_transaccion_ultima_modificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incluido', models.DateField()),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('puntualidad', models.IntegerField(choices=[(1, '1 - Muy insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy satisfecho')], verbose_name='Puntualidad')),
                ('profesionalismo_tecnico', models.IntegerField(choices=[(1, '1 - Muy insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy satisfecho')], verbose_name='Profesionalismo Técnico')),
                ('calidad_instalacion', models.IntegerField(choices=[(1, '1 - Muy insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy satisfecho')], verbose_name='Calidad de la Instalación')),
                ('explicacion_servicio', models.IntegerField(choices=[(1, '1 - Muy insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy satisfecho')], verbose_name='Explicación del Servicio')),
                ('recomendaria_servicio', models.IntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'No Sabe')], verbose_name='¿Recomendaría este servicio a otros clientes?')),
                ('comentarios_adicionales', models.TextField(blank=True, null=True, verbose_name='Comentarios Adicionales')),
                ('copia_documento', models.BooleanField(verbose_name='El tecnico entrego copia del Acuerdo del Usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remesas.cliente')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
    ]
