# Generated by Django 5.0.6 on 2024-08-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molestarClientes', '0002_tecnico_formulario_tecnico_instalador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='copia_documento',
            field=models.BooleanField(default=False, verbose_name='El técnico entregó copia del Acuerdo del Usuario al Cliente'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tecnico_instalador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='molestarClientes.tecnico', verbose_name='Técnico instalador'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='tec_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
