# Generated by Django 5.0.6 on 2024-08-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molestarClientes', '0003_alter_formulario_copia_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='cobrado',
            field=models.PositiveIntegerField(default=0, verbose_name='Valor Cobrado'),
        ),
    ]
