# Generated by Django 5.0.6 on 2024-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molestarClientes', '0005_remove_formulario_profesionalismo_tecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='explicacion_pagos',
            field=models.BooleanField(default=False, verbose_name='Explicación de los Pagos'),
        ),
    ]
