# Generated by Django 5.0.6 on 2024-08-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molestarClientes', '0006_alter_formulario_explicacion_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Terminado')], default=1),
        ),
    ]
